test = {   'name': 'q3_4',
    'points': None,
    'suites': [   {   'cases': [   {'code': ">>> # Check your column labels and spelling\n>>> largest.labels == ('name', 'poverty_total')\nTrue", 'hidden': False, 'locked': False},
                                   {   'code': ">>> # India is the country with the largest number of people living\n>>> # in extreme poverty.\n>>> largest.column(0).item(0) == 'India'\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> # The table should contain exactly 10 rows.\n>>> largest.num_rows == 10\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': '>>> all(np.isclose(largest.take(np.arange(3)).column(1), make_array(2.90881638e+08, 9.88911670e+07, 8.39446430e+07)))\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
