test = {   'name': 'q1_2_5',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> monthly_increases.num_rows == 12\nTrue', 'hidden': False, 'locked': False},
                                   {'code': ">>> monthly_increases.labels == ('Month', 'Past', 'Present', 'Increase')\nTrue", 'hidden': False, 'locked': False},
                                   {   'code': ">>> # Make sure your table is sorted from January to December.\n>>> monthly_increases.row(2).item('Month') == '03 (Mar)'\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': ">>> np.isclose(monthly_increases.row(2).item('Past'), 74.649920676890531)\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> np.isclose(monthly_increases.row(2).item('Present'), 75.979569892473123)\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
