test = {   'name': 'q2_1_4',
    'points': [0, 0, 0],
    'suites': [   {   'cases': [   {'code': ">>> set(close_movies.labels) >= {'Genre', 'Title', 'feel', 'water'}\n", 'hidden': False, 'locked': False},
                                   {'code': '>>> close_movies.num_rows == 5\n', 'hidden': False, 'locked': False},
                                   {   'code': '>>> close_movies.column("Title").item(0) != "monty python and the holy grail" # Make sure that you are using the training set.\n',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
