test = {   'name': 'q3_1_8',
    'points': [0, 1, 1, 1],
    'suites': [   {   'cases': [   {'code': ">>> genre_and_distances.labels == ('Genre', 'Distance')\n", 'hidden': False, 'locked': False},
                                   {'code': '>>> genre_and_distances.num_rows == train_movies.num_rows\n', 'hidden': False, 'locked': False},
                                   {'code': ">>> print(genre_and_distances.group('Genre'))\n", 'hidden': False, 'locked': False},
                                   {   'code': ">>> np.allclose(genre_and_distances.column('Distance'), sorted(fast_distances(test_my_features.row(0), train_my_features)))\n",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
