test = {   'name': 'q3_3_1',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> 0 <= proportion_correct <= 1\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': ">>> r = np.count_nonzero(test_guesses == test_movies.column('Genre')) / test_movies.num_rows\n>>> proportion_correct == r\nTrue",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
