test = {   'name': 'q1_1',
    'points': None,
    'suites': [   {   'cases': [   {'code': ">>> # Looks like you haven't started yet\n>>> type(b_pop) != type(...)\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> # Check your column labels and spelling\n>>> b_pop.labels == ('time', 'population_total')\nTrue", 'hidden': False, 'locked': False},
                                   {   'code': '>>> # Times should range from 1970 through 2015\n>>> all(b_pop.sort("time").column("time") == np.arange(1970, 2016))\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> # See if you selected the right three-letter code!\n>>> b_pop.sort("time", descending=True).column("population_total").item(0) == 160995642\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> b_pop.sort("time").column("population_total").item(0) == 65048701\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
